apiVersion: apps/v1

kind: Deployment

metadata:

  name: nginx-deployment

  labels:

    app: nginx

spec:

  replicas: 2

  selector:

    matchLabels:

      app: nginx

  template:

    metadata:

      labels:

        app: nginx

    spec:

      containers:

      - name: nginx

        image: 645624701308.dkr.ecr.ap-northeast-2.amazonaws.com/my-ecr:SAMPLE-PROJECT-1  

        ports:

        - containerPort: 80
